= Splunk Connector Release Notes

Make it easy to send data from your third party applications directly into the Splunk Index, and perform searches directly on the Splunk Enterprise Server from your system of choice.

*Guide:* link:user-guide.adoc[Link to Guide]

== 1.0.1 - April 22, 2016

- Version Compatibility
- Migrating from Older Versions
- Features
- Fixed in this Release
- Known Issues
- Support Resources

=== Version Compatibility

[width="100%", cols="2", options="header"]
|===
|Software |Version
|Mule Runtime |3.5.3 and above
|Splunk Enterprise |6.2 and above
|===

=== Migrating from Older Versions

If you’re currently using the Splunk Connector 1.0.0 to migrate to this connector you need to:

- Upgrade to at least Mule Runtime 3.5.3
- Install the new connector from Exchange

=== Features

- No new features

=== Fixed in this Release

- Splunk SDK 1.3.0 did not support JDK 1.8 out-of-the-box, due to a change in SSL cipher handling. New release switches to TLS1.2 instead of SSLv3 as recommended by Splunk.
- testConnection was not correctly detecting expired tokens, so connections would error after the token expiry time.

=== Known Issues

- User Management APIs are not currently supported
- Realtime searches never terminate, so will run until the connector is terminated.

=== Support Resources
- Splunk SDK for Java v 1.5.0 - http://dev.splunk.com/view/java-sdk/SP-CAAAECN
- API Documentation is available at http://whitesky-labs.github.io/splunk-connector/apidocs/mule/splunk-config.html
- Read more about http://www.mulesoft.org/documentation/display/current/Anypoint+Connectors