# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            WhiteSky Labs
tagline:          Splunk Connector Documentation
url:              http://whitesky-labs.github.io/splunk-connector/documentation/
paginate:         1
baseurl:          /
author:
  name:           WhiteSky Labs
  url:            https://twitter.com/whitesky-labs
  email:          support@whiteskylabs.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/whitesky-labs/splunk-connector
